# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/garzol/git/wiflip_tracer/ui/reprog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReprogDialog(object):
    def setupUi(self, ReprogDialog):
        ReprogDialog.setObjectName("ReprogDialog")
        ReprogDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReprogDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ReprogDialog)
        self.groupBox.setObjectName("groupBox")
        self.toolButton_reprog = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_reprog.setGeometry(QtCore.QRect(10, 30, 41, 41))
        self.toolButton_reprog.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_reprog.setAutoRaise(True)
        self.toolButton_reprog.setObjectName("toolButton_reprog")
        self.toolButton_reset_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_reset_2.setGeometry(QtCore.QRect(130, 30, 41, 41))
        self.toolButton_reset_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_reset_2.setAutoRaise(True)
        self.toolButton_reset_2.setObjectName("toolButton_reset_2")
        self.toolButton_loadbin = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_loadbin.setGeometry(QtCore.QRect(70, 31, 41, 41))
        self.toolButton_loadbin.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_loadbin.setAutoRaise(True)
        self.toolButton_loadbin.setObjectName("toolButton_loadbin")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label.setObjectName("label")
        self.label_crc = QtWidgets.QLabel(self.groupBox)
        self.label_crc.setGeometry(QtCore.QRect(130, 110, 71, 16))
        self.label_crc.setText("")
        self.label_crc.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_crc.setObjectName("label_crc")
        self.label_error = QtWidgets.QLabel(self.groupBox)
        self.label_error.setGeometry(QtCore.QRect(20, 150, 311, 41))
        self.label_error.setText("")
        self.label_error.setWordWrap(True)
        self.label_error.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(ReprogDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ReprogDialog)
        self.buttonBox.accepted.connect(ReprogDialog.accept)
        self.buttonBox.rejected.connect(ReprogDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReprogDialog)

    def retranslateUi(self, ReprogDialog):
        _translate = QtCore.QCoreApplication.translate
        ReprogDialog.setWindowTitle(_translate("ReprogDialog", "Reprog"))
        self.groupBox.setTitle(_translate("ReprogDialog", "Reprog panel"))
        self.toolButton_reprog.setText(_translate("ReprogDialog", "RPG"))
        self.toolButton_reset_2.setText(_translate("ReprogDialog", "Reset"))
        self.toolButton_loadbin.setText(_translate("ReprogDialog", "Load..."))
        self.label.setText(_translate("ReprogDialog", "Fletcher\'s CRC :"))
